package com.fiona.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("book", "id", Book.class);
		arp.addMapping("city", "id", City.class);
		arp.addMapping("person", "id", Person.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("user", "id", User.class);
	}
}

