package com.fiona.model;

import com.fiona.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public final static User dao = new User();
}
