package com.fiona.model;

import com.fiona.model.base.BaseUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Users extends BaseUsers<Users> {
	public static Users dao = new Users(); //静态成员，调用成员方法，不用每次new一个新成员再调用
}
